name: Benchmark Comment on PR

on:
    pull_request:
        paths:
            - 'test/**'
            - '!test/**/*.test.ts'
            - '!test/**/*.spec.ts'
    workflow_dispatch:
        inputs:
            pr_number:
                description: 'PR number to run benchmark on'
                required: false
                type: number

jobs:
    create-benchmark-comment:
        name: create benchmark comment
        runs-on: ubuntu-latest
        steps:
            - name: Git
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Setup node
              uses: NaverPayDev/benchmark-actions@main
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PACKAGE_MANAGER: 'pnpm'
                  TARGET: 'comment'
                  SOURCE_ROOT: 'test'
                  PR_NUMBER: ${{ github.event.inputs.pr_number }}
