name: Benchmark Readme

on:
    workflow_dispatch:
        inputs:
            target:
                description: 'target'
                default: 'markdown'
                required: true
                type: string
jobs:
    create-benchmark-readme:
        name: create benchmark comment
        runs-on: ubuntu-latest
        steps:
            - name: Git
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Setup node
              uses: NaverPayDev/benchmark-actions@main
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PACKAGE_MANAGER: 'pnpm'
                  TARGET: ${{ github.event.inputs.target }}
                  SOURCE_ROOT: 'test'
